@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoZW5kcml4IiwiaWQiOjEsImlhdCI6MTY1MzE3NDIzMX0.aQv9WuJq-2bfpnbewKaEYmAPBW-r6XpnofIsIwmrv3s

### POST login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "chendrix",
    "password": "secret"
}

### GET all users
GET http://localhost:3001/api/users

### POST user
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
  "username": "tomado",
  "name": "Tom Ado"
}