### GET all persons
GET http://localhost:3001/api/persons

### GET person 1
GET http://localhost:3001/api/persons/1

### POST new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Chris",
    "number": "555-555-5555"
}

### POST person 999
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "id": 999,
    "name": "Person 999",
    "number": "999-999-9999"
}
### GET person 999
GET http://localhost:3001/api/persons/999
### DELETE person 999
DELETE http://localhost:3001/api/persons/999