### GET all persons
GET http://localhost:3001/api/persons

### GET person
GET http://localhost:3001/api/persons/61a44a39557b551e1353066a

### POST new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Chris",
    "number": "555-555-5555"
}

### POST person 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Chris Hendrix",
    "number": "999-999-9999"
}

### GET person 999
GET http://localhost:3001/api/persons/999

### DELETE person 999
DELETE http://localhost:3001/api/persons/999

### PUT updated person 1
PUT http://localhost:3001/api/persons/61a44a39557b551e1353066a
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "555-555555"
}

### PUT updated person 1
PUT http://localhost:3001/api/persons/61a44a39557b551e1353066a
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "666-666666"
}