### GET all blogs
GET http://localhost:3001/api/blogs

### GET blog by id
GET http://localhost:3001/api/blogs/1

### DELETE blog by id
DELETE http://localhost:3001/api/blogs/3

### POST blog
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "author": "Free Code",
  "url": "freecodecamp.com",
  "title": "FreeCodeCamp",
  "likes": 0
}

### PUT blog by id
PUT http://localhost:3001/api/blogs/1 HTTP/1.1
content-type: application/json

{
  "likes": 1
}