### GET all blogs
GET http://localhost:3001/api/blogs

### GET blog 1
GET http://localhost:3001/api/blogs/1

### DELETE blog 1
DELETE http://localhost:3001/api/blogs/3

### POST blog
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "author": "Free Code",
  "url": "freecodecamp.com",
  "title": "FreeCodeCamp",
  "likes": 0
}