### GET all persons
GET http://localhost:3001/api/persons

### GET person 1
GET http://localhost:3001/api/persons/1

### POST person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Chris",
    "number": "555-555-5555"
}